// Generates the per-character and per-skill prompts (docs/prompts/*.md) from the same specs the game draws with.
// usage: node tools/gen-prompts.js
const fs = require('fs'), path = require('path'), vm = require('vm');
const ROOT = path.join(__dirname, '..'), SRC = path.join(ROOT, 'src'), OUT = path.join(ROOT, 'docs', 'prompts');
const ctx = { window: { MC: {} }, Math, Object, Array, JSON, Uint8Array, Float32Array, Map, Set, console };
ctx.window.window = ctx.window; vm.createContext(ctx);
['mc-db.js', 'mc-px16.js', 'mc-px16-hum.js', 'mc-px16-spec.js', 'mc-px16-cast.js', 'mc-px16-fx.js'].forEach(f => vm.runInContext(fs.readFileSync(path.join(SRC, f), 'utf8'), ctx, { filename: f }));
const M = ctx.window.MC, P = M.P16, DB = M.DB, TDB = M.TDB, RAMP = P.RAMP;
const HEROES = { watchman: ['守夜人', 'night watchman leader', '照夜', '灯盾猛击'], widow: ['赌徒寡妇', 'gambling widow leader', '梭哈', '致命一掷'], nun: ['驱魔修女', 'exorcist nun leader', '圣咏', '圣光祷言'], butcherlord: ['屠宰场主', 'slaughterhouse lord leader', '血祭', '剁骨旋风'], clockmaker: ['钟表匠', 'clockmaker leader', '倒带', '停摆'], cremator: ['焚尸人', 'cremator leader', '火葬', '焚身'], militia: ['民兵', 'base militia soldier'] };
const Q = ['普通', '稀有', '史诗', '传说'];
const words = (k) => k.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/([A-Z])([A-Z][a-z])/g, '$1 $2').toLowerCase();
const RACE_EN = { 兽人: 'orc', 不死: 'undead', 骷髅: 'skeleton', 人类: 'human', 精灵: 'elf', 僵尸: 'zombie', 科技: 'tech', 恶魔: 'demon', 自然: 'nature', 虚空: 'void', 混沌: 'chaos', 野兽: 'beast', 英雄: 'hero' };
const SCENE = { 兽人: 'dusk canyon with a red sky, a few 1px stars, a rock ledge floor line', 不死: 'moonlit graveyard, blue night sky, twinkling 1px stars, a crooked fence and a stone floor line', 骷髅: 'crypt at night, dark teal sky, a moon, tombstone silhouettes on a stone floor line', 人类: 'castle courtyard at night, deep blue sky, twinkling 1px stars, moon, flagstone floor line', 精灵: 'forest clearing at night, green-black sky, fireflies as single pixels, grass floor line', 僵尸: 'swamp at night, sickly green haze, moon behind clouds, mud floor line', 科技: 'factory rooftop at night, steel-blue sky, blinking antenna lights, metal floor line', 恶魔: 'hellish night, ember-red sky, drifting 1px embers, cracked basalt floor line', 自然: 'jungle at night, deep green sky, a moon, leafy floor line', 虚空: 'void rift, violet-black sky with twinkling purple stars, crystal floor line', 混沌: 'burning battlefield, blood-red sky, ash flakes, scorched floor line', 野兽: 'wild plains at night, dark sky, a big moon, grass floor line', 英雄: 'a quiet street at midnight, deep blue sky, a lamp post, cobble floor line' };
const RIG_EN = {
  hum: (s) => { const bits = []; const build = { slim: 'slim', norm: '', heavy: 'heavy-set', giant: 'hulking giant', short: 'short, stocky' }[s.build || 'norm'] || '';
    const head = { human: '', skull: 'a skull head with glowing eye sockets and a row of teeth', orc: 'a green-skinned orc face with a tusk', elf: 'a pointed-ear elf face', zombie: 'a stitched zombie face', demon: 'a demon face with fangs', ghost: 'a hollow face with two glowing eyes', robot: 'a boxy robot head with a glowing visor', bird: 'an eagle head with a hooked beak', frog: 'a wide frog head with bulging eyes', lizard: 'a scaly lizard head with a snout', wolf: 'a wolf head', pig: 'a pig head', bear: 'a bear head', stone: 'a stone head with glowing eyes' }[s.head || 'human'];
    bits.push((build ? build + ' ' : '') + 'humanoid' + (head ? ' with ' + head : ''));
    if (s.hair && s.hair !== 'none' && s.hair !== 'bald') bits.push(s.hair + ' hair'); if (s.beard) bits.push(s.beard === 'viking' ? 'a braided viking beard' : s.beard + ' beard');
    const hat = { hood: 'a hood', wizard: 'a pointed wizard hat with a bend', witch: 'a wide-brim witch hat', helm: 'an open helmet', greathelm: 'a great helm with an eye slit', helmH: 'a horned helmet', viking: 'a horned viking helm', helmP: 'a plumed helmet', crown: 'a gold crown', straw: 'a wide straw hat', cap: 'a cap', bandana: 'a bandana with trailing tails', turban: 'a turban with a gem', miter: 'a tall bishop miter', tophat: 'a top hat', hornsD: 'curved demon horns', antlers: 'antlers', goggles: 'brass goggles', feather: 'a feathered headband', veil: 'a veil', skullcap: 'a bone skullcap', mask: 'a tribal mask', flame: 'hair made of flickering fire' }[s.hat];
    if (hat) bits.push('wearing ' + hat);
    const body = { robe: 'a long two-shade robe with a trim band', priest: 'a priest robe with a stole', dress: 'a flared dress', armor: 'plate armour with pauldrons and a belt', heavyarmor: 'heavy plate armour with big pauldrons', bare: 'a bare chest, belt and trousers', ribs: 'an exposed ribcage and bone limbs', coat: 'a long coat with a centre seam', rags: 'ragged cloth', vest: 'an open vest over bare skin', tunic: 'a belted tunic' }[s.body || 'tunic'];
    bits.push(body); if (s.cape) bits.push('a cape that sways behind'); if (s.wings) bits.push(s.wings + ' wings'); if (s.tail) bits.push('a ' + s.tail + ' tail'); if (s.quiver) bits.push('a quiver on the back'); if (s.pack) bits.push('a backpack'); if (s.scarf) bits.push('a trailing scarf'); if (s.halo) bits.push('a floating gold halo'); if (s.hover) bits.push('no legs — the body tapers into floating wisps');
    const w = { sword: 'a one-handed sword', katana: 'a slim katana', greatsword: 'a two-handed greatsword', dagger: 'a dagger', axe: 'an axe', mace: 'a flanged mace', club: 'a heavy club', hammer: 'a war hammer', flail: 'a flail on a chain', scythe: 'a long scythe', sickle: 'a sickle', spear: 'a spear', pike: 'a long pike', lance: 'a jousting lance', trident: 'a gold trident', banner: 'a war banner', staff: 'a staff with a gem at the tip', wand: 'a short wand with a star gem', torch: 'a burning torch', bow: 'a recurve bow', crossbow: 'a crossbow', gun: 'a pistol', rifle: 'a long rifle', cannon: 'a shoulder cannon', book: 'an open spell book', orb: 'a floating orb above the hand', bag: 'a coin bag', shuriken: 'a shuriken', fan: 'a folding fan', claws: 'claws', fist: 'bare fists' }[s.weapon];
    if (w) bits.push('holding ' + w); if (s.shield) bits.push('a ' + s.shield + ' shield on the off arm');
    return bits.join(', '); },
  beast: (s) => ['a chibi ' + s.kind + ' with a short deep body (chest bigger than the hips), a big head held highest, thick legs and pointed ears', s.tusks || s.kind === 'boar' ? 'tusks' : '', s.spots ? 'spots' : '', s.spikes ? 'bone spikes along the back' : '', s.crown ? 'a small gold crown' : '', s.flameMane ? 'a mane of flickering fire' : '', s.saddle ? 'a saddle' : '', s.armor ? 'armour plates' : '', s.horns ? 'horns' : '', s.kind === 'cerberus' ? 'three heads' : ''].filter(Boolean).join(', '),
  dragon: (s) => s.eastern ? 'a floating eastern dragon: a long S-curved serpent body with belly plates, small clawed legs, whiskers and antler horns' : ['a compact dragon' + (s.fly !== false ? ' hovering' : ' standing on four legs') + ' with an S-curved neck holding the head high', s.noWings ? 'no wings' : 'two big raised membrane wings with arm bones', 'a curled tail with a spade tip', 'back spines and horns', s.bones ? 'visible rib bones' : ''].filter(Boolean).join(', '),
  serpent: () => 'a floating serpent dragon', bird: (s) => 'a round ' + s.kind + (s.fly ? ' in flight with spread wings' : ' with folded wings, beak and thin legs'),
  fly: (s) => ({ bat: 'a bat with big membrane wings' + (s.gun ? ' and a gun strapped under it' : ''), manta: 'a flying manta ray with undulating wing edges', warp: 'an arrow-shaped warp craft with engine flames' })[s.kind] || 'a flyer',
  copter: (s) => 'a small helicopter with a glass cockpit, a spinning rotor and a gun' + (s.pilot ? ', a goblin pilot inside' : ''),
  spider: (s) => 'a spider with a round abdomen, eight jointed legs and a cluster of glowing eyes' + (s.crown ? ', wearing a crown' : ''), crab: (s) => 'a crab with a round shell, stalk eyes and snapping claws' + (s.hat ? ', wearing a wizard hat' : ''), worm: (s) => 'a segmented worm that humps along' + (s.sickle ? ' with sickle blades' : '') + (s.crown ? ', wearing a crown' : ''),
  snail: (s) => 'a snail with a spiral shell and eye stalks' + (s.spikes ? ', the shell ringed with spikes' : ''), turtle: (s) => 'a turtle with a domed shell' + (s.dragon ? ', dragon horns and back spines' : ''), mole: (s) => 'a round mole with digging claws' + (s.hat ? ' and a hard hat' : '') + (s.quills ? ' covered in quills' : ''), lizard: (s) => 'a low lizard with a long tail' + (s.gems ? ' and gems along its back' : ''), snake: () => 'a coiled snake with a raised hooded head',
  eye: (s) => 'a floating eyeball with tentacles' + (s.wings ? ' and bat wings' : '') + (s.crown ? ', wearing a crown' : ''), kraken: () => 'a kraken head with six curling tentacles', bot: (s) => 'a floating round robot with a glowing visor, an antenna and thruster flames' + (s.wingsB ? ', small metal wings' : ''), mechwalker: (s) => 'a two-legged war machine with a ' + (s.gun === 'cannon' ? 'heavy cannon' : 'laser gun') + ' body',
  siege: (s) => ({ catapult: 'a catapult', trebuchet: 'a trebuchet', ram: 'a covered battering ram on wheels' })[s.kind] + (s.legs ? ' that walks on wooden legs' : ''), tower: (s) => 'a stone tower with battlements and a glowing window, topped by ' + ({ crystal: 'a floating crystal', flame: 'an eternal flame', orb: 'an orb', storm: 'a small storm cloud with lightning', portal: 'a swirling portal' })[s.kind] + (s.vines ? ', vines climbing the walls' : ''),
  egg: () => 'a huge egg-shaped stone with glowing cracks', tree: () => 'a living tree with a face on the trunk, a round canopy and glowing fruit', mimic: () => 'a treasure chest monster with a toothy lid, a tongue and little legs', centaur: (s) => 'a centaur: a horse body with a ' + (s.body === 'armor' ? 'armoured' : 'bare-chested') + ' humanoid torso' + (s.hat ? ' wearing ' + s.hat : '') + ', holding ' + (s.weapon || 'a weapon'), dino: () => 'an upright dinosaur with a big toothy head and tiny arms',
};
const CAST_EN = { spiral: 'the gathered sparks explode outward in a ring and a bolt flies across the scene', heal: 'plus-shaped motes pour over the target and a soft ring rises from it', fire: 'a fireball flies across the scene and bursts into embers', frost: 'the ice shards shoot out and a frost ring crackles on the ground', bolt: 'a zigzag lightning bolt forks from the focus to the target and jumps on', shield: 'a pixel dome closes over the target, flashes and holds', summon: 'the circle flashes and a pillar of light rises; the summoned unit pops in', poison: 'a toxic cloud puffs over the target with drifting bubbles', blade: 'blades rain down onto the target area and stick in the ground', buff: 'a fountain of particles bursts upward and a ring expands through the allies', shadow: 'dark wisps lash out to the target and burst', beam: 'a straight beam shoots to the target and splashes', coin: 'gold coins burst up, spin and rain down', nova: 'a flat ring of particles expands outward along the floor', meteor: 'a meteor falls from the top-left and explodes into sparks on impact' };
const PAT_EN = { spiral: 'sparks spiral inward to the focus point', heal: 'small plus-shaped motes rise from the ground around the caster', fire: 'embers rise from the feet and flicker', frost: 'ice shards orbit the focus', bolt: 'a crackling zigzag bolt forks towards the target', shield: 'a ring of particles closes into a dome then expands', summon: 'a particle circle draws itself on the ground and a pillar of light rises from it', poison: 'bubbles and slow drifting clouds', blade: 'blades rain down onto the target area and stick in the ground', buff: 'a fountain of particles bursts upward and a ring expands', shadow: 'dark wisps and magic sparks curl inward', beam: 'a straight beam of particles shoots to the target and splashes', coin: 'gold coins burst up and fall', nova: 'a flat ring of particles expands outward', meteor: 'a meteor falls from the top-left and explodes into sparks' };
const pal = (names) => [...new Set(names)].filter(n => RAMP[n]).map(n => n + ' ' + RAMP[n].slice(1, 4).join(' ')).join('; ');
const focusEn = (s) => s.rig === 'hum' ? ({ staff: 'the gem at the tip of the staff', wand: 'the wand star', orb: 'the orb', book: 'the glyph above the open book', torch: 'the torch flame', fan: 'the fan edge', bag: 'the coin bag', claws: 'the claw tips', scythe: 'the scythe blade', banner: 'the banner top', bow: 'the nocked arrow', crossbow: 'the bolt', gun: 'the muzzle', rifle: 'the muzzle', cannon: 'the muzzle' }[s.weapon] || 'the weapon tip') : s.rig === 'eye' ? 'the iris' : s.rig === 'tower' ? 'the top of the tower' : 'the mouth';
function charPrompt(key) {
  const s = P.spec(key), d = DB[key], H = HEROES[key], name = d ? d.n : H[0], race = s.race || (d && d.race) || '英雄';
  const kindEn = s.rig === 'hum' ? words(key) : (s.kind || s.rig) + ' called “' + words(key) + '”', subj = H ? H[1] : (RACE_EN[race] ? RACE_EN[race] + ' ' : '') + kindEn;
  const rig = (RIG_EN[s.rig] || RIG_EN.hum)(s);
  const raw = P.SPECS[key] || {}, hum = s.rig === 'hum' || s.rig === 'centaur';
  const slots = (hum ? ['skin', 'cloth', 'cloth2', 'pants', 'trim'].concat(s.hair || s.beard ? ['hair'] : [], s.hat ? ['hat'] : [], s.cape ? ['cape'] : [], s.wings ? ['wing'] : [], s.weapon || s.shield || /armor/.test(s.body || '') ? ['metal'] : []) : ['fur', 'fur2', 'belly']).concat(Object.keys(raw.mat || {}));
  const mats = [...new Set(slots.map(k => s.mat[k]).filter(r => RAMP[r] && r !== 'ink'))].slice(0, 7);
  const rec = d ? ((d.tr || []).map(t => P.FX[t.replace(/^Summon|Trait$/g, '')]).find(Boolean)) : P.FX['P:' + key];
  const W = Math.ceil(s.S * 1.2), Hh = Math.round(s.S * 1.15);
  const weaponAtk = { melee: 'wind the weapon back overhead, swing it down across the body, follow through low', heavy: 'heave the heavy weapon far back, smash it down with the body leaning in', pole: 'pull the shaft back, thrust it straight forward, recoil', staff: 'raise the staff, thrust it forward so the gem flares', bow: 'draw the string to the cheek with an arrow nocked, release (string snaps straight), relax', gun: 'aim, fire with a 2-pixel muzzle flash and recoil, settle', hand: 'raise the hand, strike forward, pull back' }[s.rig === 'hum' ? P.FAM[s.weapon || 'none'] : ''] || (s.rig === 'tower' ? 'the top glows, recoils and fires a bolt' : 'crouch, lunge forward with the jaw / claws open, then settle back');
  return [
    '### ' + name + '（' + key + '）' + (d ? ' · ' + race + ' · ' + (d.voc || '—') + ' · ' + Q[d.q || 0] : ' · 领袖'), d && d.desc ? '> ' + d.desc : '', '',
    '```text',
    'Create a single self-contained HTML file that renders an animated pixel art sprite of ' + (/^[aeiou]/.test(subj) ? 'an ' : 'a ') + subj + ' (“' + name + '”) ' + (rec ? 'casting its skill' : 'fighting') + ', using vanilla JavaScript and Canvas 2D. No external assets, libraries, or network requests.', '',
    'RENDERING',
    '- Draw everything to an offscreen canvas at a fixed logical resolution of 128x96, then blit to a fullscreen display canvas scaled by the largest integer factor that fits the window, centered, with imageSmoothingEnabled = false and CSS image-rendering: pixelated.',
    '- All drawing snaps to integer coordinates on the logical canvas. No sub-pixel positions, anti-aliasing, gradients, or shadowBlur.',
    '- Fixed palette of ~24 hex colors built from these ramps (shadow / base / light): ' + pal(mats.concat([s.magic || 'arcane', 'ink'])) + '. Every pixel comes from this palette.', '',
    'CHARACTER',
    '- Build the character procedurally from filled rects and pixel runs, ~' + W + 'x' + Hh + ' logical pixels: ' + rig + '.',
    '- Every part is two-shade (base + shadow on the lower-right edge, a light edge on the upper-left, a highlight on metal and gems) inside a darker selective outline.',
    '- Parameterize the pose (' + (s.rig === 'hum' ? 'arm angle, weapon angle, lean, head tilt, ' + (s.hover ? 'hover height' : 'leg stride') + ', cloth sway' : 'body bob, head raise, jaw open, leg stride, tail / wing sway') + '). Animate parameters smoothly, then quantize to the pixel grid each frame so motion reads at an 8-12 fps pixel animation feel even though the loop runs at 60fps.', '',
    'ANIMATION',
    '- Looping state machine: IDLE (2-frame bob, cloth / tail sway) -> WALK (4-frame stride) -> ATTACK (' + weaponAtk + ') -> CHARGE (' + (s.rig === 'hum' ? 'raise the ' + (s.weapon || 'hands') + ' overhead' : 'rear up, head raised') + ', ' + focusEn(s) + ' flickers, ' + PAT_EN[rec ? rec.ch : 'spiral'] + ') -> CAST (bright burst, ' + CAST_EN[rec ? rec.cs : 'spiral'] + ', 1-2 pixel screen shake) -> RECOVER (settle back) -> HURT (1-frame recoil with a white flash). Ease pose parameters between keyframes.',
    '- Pooled allocation-free particle system: preallocate and reuse. Particles step their palette index from white to ' + (rec ? rec.ramp : s.magic) + ' (' + RAMP[rec ? rec.ramp : s.magic || 'arcane'].slice(2).reverse().join(' → ') + ') to dark before despawn. Snap particle positions to the grid when drawing.',
    '- Fixed 60hz timestep update with rAF rendering. Zero object allocation inside the loop.', '',
    'SCENE',
    '- Minimal background: ' + (SCENE[race] || SCENE['人类']) + '. Character silhouette must read clearly.',
    '- Subtle 1px rim light on the character from ' + focusEn(s) + ' in ' + (rec ? rec.ramp : s.magic || 'arcane') + ', brightening during CHARGE and CAST.', '',
    'QUALITY BAR',
    '- Crisp pixels at any window size, seamless loop, stable 60fps, readable silhouette. Should look like a polished 16-bit sprite animation, not vector shapes scaled down.',
    '```', ''].join('\n');
}
function skillPrompt(id, rec) {
  const hero = /^[LP]:/.test(id), hk = hero ? id.slice(2) : null, isSig = !hero && !TDB['Summon' + id + 'Trait'];
  const T = !hero && !isSig ? TDB['Summon' + id + 'Trait'] : null;
  const name = hero ? HEROES[hk][id[0] === 'L' ? 2 : 3] : T ? T.n : ({ charge: '冲锋盾击', whirl: '旋风斩', volley: '箭雨', fireball: '陨石术', frost: '霜冻新星', chain: '闪电链', holy: '圣光审判', gold: '金币风暴', maul: '猛扑' })[id] || id;
  const owners = hero ? [HEROES[hk][0]] : T ? Object.keys(DB).filter(k => (DB[k].tr || []).includes('Summon' + id + 'Trait')).map(k => DB[k].n) : ['招牌技能（按职业分配给没有法力技能的单位）'];
  const kind = hero ? (id[0] === 'L' ? '军团技能（领袖在场外点击释放）' : '个人技能（领袖上场后自动释放）') : isSig ? '招牌技能' : '单位技能';
  return ['### ' + name + '（' + id + '） · ' + kind, '持有者：' + owners.join('、'), T && T.d ? '> ' + T.d : '', '> 画面：' + rec.d, '',
    '```text',
    'Create a single self-contained HTML file that renders the pixel art skill effect “' + name + '” from 午夜机台, cast by a small pixel caster at the left of the scene onto a dummy target at the right, using vanilla JavaScript and Canvas 2D. No external assets, libraries, or network requests.', '',
    'RENDERING',
    '- Draw everything to an offscreen canvas at a fixed logical resolution of 128x96, then blit scaled by the largest integer factor that fits the window, centered, imageSmoothingEnabled = false, CSS image-rendering: pixelated.',
    '- Integer coordinates only; no anti-aliasing, gradients or shadowBlur. Fixed palette: ink ' + RAMP.ink.slice(0, 3).join(' ') + ' plus the ' + rec.ramp + ' ramp ' + RAMP[rec.ramp].join(' ') + ' and white.', '',
    'EFFECT',
    '- Visual intent (from the game): ' + rec.d,
    '- CHARGE (~0.5-0.9s): ' + PAT_EN[rec.ch] + '; the caster raises its hands / weapon and a 1px rim light in ' + rec.ramp + ' brightens on its silhouette.',
    '- CAST: ' + CAST_EN[rec.cs] + '; bright burst at the focus point, 1-2 pixel screen shake, the target flashes white for one frame.',
    '- RECOVER: particles fade out; the caster settles back to idle.',
    '- Pooled allocation-free particles (preallocate ~512, reuse). Each particle steps its palette index white → ' + RAMP[rec.ramp].slice(1, 5).reverse().join(' → ') + ' before despawn; draw them snapped to the grid, 1-3 px squares.',
    '- Loop the whole sequence seamlessly: IDLE -> CHARGE -> CAST -> RECOVER. Fixed 60hz timestep, rAF rendering, zero allocation in the loop; pose parameters quantized so it reads at 8-12 fps.', '',
    'QUALITY BAR',
    '- Crisp pixels at any window size, stable 60fps. Should look like a polished 16-bit skill animation, not vector shapes scaled down.',
    '```', ''].filter(x => x !== null).join('\n');
}
fs.mkdirSync(OUT, { recursive: true });
const keys = Object.keys(HEROES).concat(Object.keys(DB));
const byRace = {}; keys.forEach(k => { const r = HEROES[k] ? '领袖与民兵' : DB[k].race; (byRace[r] = byRace[r] || []).push(k); });
let md = '# 午夜机台 · 角色 prompt\n\n每个角色一段，按「动画像素法师」的 prompt 写法：固定 128×96 逻辑分辨率、整数放大、固定调色板、程序化像素拼装、IDLE→CHARGE→CAST→RECOVER 状态机、池化粒子、1px 轮廓光。\n游戏里的实现就是这些描述：`src/mc-px16-cast.js` 是每个角色的数据版 prompt，`src/mc-px16-hum.js` / `mc-px16-rigs.js` 是骨架，`src/mc-px16-fx.js` 是技能特效配方。本文件由 `node tools/gen-prompts.js` 从同一份数据生成，改角色请改数据后重新生成。\n\n共 ' + keys.length + ' 个角色。\n\n';
Object.keys(byRace).forEach(r => { md += '## ' + r + '\n\n'; byRace[r].forEach(k => { md += charPrompt(k) + '\n'; }); });
fs.writeFileSync(path.join(OUT, 'characters.md'), md);
let sk = '# 午夜机台 · 技能 prompt\n\n每个会施放的技能一段：蓄力花样 + 施放花样 + 调色板。游戏里由 `src/mc-px16-fx.js` 的配方表驱动，本文件由 `node tools/gen-prompts.js` 生成。\n\n';
const ids = Object.keys(P.FX); sk += '共 ' + ids.length + ' 个技能。\n\n';
[['单位技能', ids.filter(i => TDB['Summon' + i + 'Trait'])], ['招牌技能', ids.filter(i => !TDB['Summon' + i + 'Trait'] && !/^[LP]:/.test(i))], ['领袖技能', ids.filter(i => /^[LP]:/.test(i))]].forEach(([t, list]) => { sk += '## ' + t + '\n\n'; list.forEach(i => { sk += skillPrompt(i, P.FX[i]) + '\n'; }); });
fs.writeFileSync(path.join(OUT, 'skills.md'), sk);
console.log('characters', keys.length, 'skills', ids.length, '->', path.relative(ROOT, OUT));
